
spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
#mybatis
mybatis:
  type-aliases-package: com.dj.springboot.domain
  mapper-locations: classpath:mapper/*.xml
