#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dj_student?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
